export const staticData = [
    {
      id: 1,
      availability: "In Stock",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/41Ef9gHiz5L._SY445_SX342_QL70_ML2_.jpg",
      link: "https://www.amazon.com/Murad-Broad-Spectrum-Mineral-Sunscreen/dp/B075S1BM4V/ref=sr_1_77?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695194332&sprefix=suns%2Caps%2C533&sr=8-77",
      price: "$69.00",
      rank: 166.54,
      rating: "4.4 out of 5 stars",
      reviews: "346 ratings",
      title: "Murad Environmental Shield City Skin Age Defense Broad Spectrum SPF 50-100% Mineral Sunscreen - Blue Light Defense - SPF 50 Environmental Defense Sunscreen - Light Sunscreen for Face",
      website: "amazon"
    }, 
    {
        id: 2,
      availability: "In Stock",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/31OczkDNwiL._SX300_SY300_QL70_ML2_.jpg",
      link: "https://www.amazon.com/sspa/click?ie=UTF8&spc=MTozNzYxNjE3OTQ4MjY4NjI3OjE2OTUxOTM5Nzc6c3BfbXRmOjMwMDA0MTQ3NjczNTUwMjo6MDo6&url=%2FOars-Alps-Everyday-Moisturizer-Hyaluronic%2Fdp%2FB08YRPSQ7M%2Fref%3Dsr_1_70_sspa%3Fcrid%3DBCICLEMKVXND%26keywords%3Dsunscreen%26qid%3D1695193976%26sprefix%3Dsuns%252Caps%252C533%26sr%3D8-70-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9tdGY%26psc%3D1",
      price: "$21.99",
      rank: 132.711,
      rating: "4.1 out of 5 stars",
      reviews: "269 ratings",
      title: "Oars + Alps SPF 37 Sunscreen and Everyday Anti Aging Face Moisturizer, Infused with Hyaluronic Acid, Vitamin E and Vitamin B5, TSA Friendly, 2 Fl Oz",
      website: "amazon"
    },
    {
        id: 3,
      availability: "In Stock",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/31ZjIHuUZML._SX300_SY300_QL70_ML2_.jpg",
      link: "https://www.amazon.com/sspa/click?ie=UTF8&spc=MTo1MzA4MjE2NzQxOTQwNjI3OjE2OTUxOTM4NjQ6c3BfbXRmOjMwMDAwNTQ4MTYyNzAwMjo6MDo6&url=%2FGood-Molecules-Sheer-Mineral-Sunscreen%2Fdp%2FB0BNC52HLN%2Fref%3Dsr_1_69_sspa%3Fcrid%3DBCICLEMKVXND%26keywords%3Dsunscreen%26qid%3D1695193864%26sprefix%3Dsuns%252Caps%252C533%26sr%3D8-69-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9tdGY%26psc%3D1",
      price: "$12.00",
      rank: 102.23,
      rating: "4.3 out of 5 stars",
      reviews: "206 ratings",
      title: "Good Molecules Sheer Mineral Sunscreen SPF 30 50ml/1.7oz - Invisible, Sheer, Zinc Oxide Sunscreen with Hyaluronic Acid - Reef-Safe, Hydrating, Non-greasy UVA/UVB Protection - Skin Care For Face",
      website: "amazon"
    },
    {
        id: 4,
      availability: "In Stock",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/312pSZ7-bXL._SX300_SY300_QL70_ML2_.jpg",
      link: "https://www.amazon.com/Haruharu-Sunscreen-1-69fl-oz-Including-Sensitive/dp/B0BZ3Q4ZD9/ref=sr_1_73?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695193864&sprefix=suns%2Caps%2C533&sr=8-73",
      price: "$12.99",
      rank: 74.111,
      rating: "4.1 out of 5 stars",
      reviews: "150 ratings",
      title: "Haruharu Wonder Black Rice Pure Mineral Relief Daily Sunscreen 50ml (1.69fl.oz), Reef Safe Formula, For All Skin Types Including Sensitive Skin",
      website: "amazon"
    },
    {
        id: 5,
      availability: "In Stock",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/312pSZ7-bXL._SX300_SY300_QL70_ML2_.jpg",
      link: "https://www.amazon.com/Haruharu-Sunscreen-1-69fl-oz-Including-Sensitive/dp/B0BZ3Q4ZD9/ref=sr_1_73?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695193976&sprefix=suns%2Caps%2C533&sr=8-73",
      price: "$12.99",
      rank: 74.111,
      rating: "4.1 out of 5 stars",
      reviews: "150 ratings",
      title: "Haruharu Wonder Black Rice Pure Mineral Relief Daily Sunscreen 50ml (1.69fl.oz), Reef Safe Formula, For All Skin Types Including Sensitive Skin",
      website: "amazon"
    },
    {
        id: 6,
      availability: "In Stock",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/312pSZ7-bXL._SX300_SY300_QL70_ML2_.jpg",
      link: "https://www.amazon.com/Haruharu-Sunscreen-1-69fl-oz-Including-Sensitive/dp/B0BZ3Q4ZD9/ref=sr_1_73?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695194088&sprefix=suns%2Caps%2C533&sr=8-73",
      price: "$12.99",
      rank: 74.111,
      rating: "4.1 out of 5 stars",
      reviews: "150 ratings",
      title: "Haruharu Wonder Black Rice Pure Mineral Relief Daily Sunscreen 50ml (1.69fl.oz), Reef Safe Formula, For All Skin Types Including Sensitive Skin",
      website: "amazon"
    },
    {
        id: 7,
      availability: "In Stock",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/312pSZ7-bXL._SX300_SY300_QL70_ML2_.jpg",
      link: "https://www.amazon.com/Haruharu-Sunscreen-1-69fl-oz-Including-Sensitive/dp/B0BZ3Q4ZD9/ref=sr_1_72?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695194220&sprefix=suns%2Caps%2C533&sr=8-72",
      price: "$12.99",
      rank: 74.111,
      rating: "4.1 out of 5 stars",
      reviews: "150 ratings",
      title: "Haruharu Wonder Black Rice Pure Mineral Relief Daily Sunscreen 50ml (1.69fl.oz), Reef Safe Formula, For All Skin Types Including Sensitive Skin",
      website: "amazon"
    },
    {
        id: 8,
      availability: "In Stock",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/312pSZ7-bXL._SX300_SY300_QL70_ML2_.jpg",
      link: "https://www.amazon.com/Haruharu-Sunscreen-1-69fl-oz-Including-Sensitive/dp/B0BZ3Q4ZD9/ref=sr_1_74?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695194332&sprefix=suns%2Caps%2C533&sr=8-74",
      price: "$12.99",
      rank: 74.111,
      rating: "4.1 out of 5 stars",
      reviews: "150 ratings",
      title: "Haruharu Wonder Black Rice Pure Mineral Relief Daily Sunscreen 50ml (1.69fl.oz), Reef Safe Formula, For All Skin Types Including Sensitive Skin",
      website: "amazon"
    },
    {
        id: 9,
      availability: "In Stock",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/41vCCia7MOL._SX300_SY300_QL70_ML2_.jpg",
      link: "https://www.amazon.com/Sunscreen-Organic-Solution-Nourishing-Protection/dp/B0CF26JJG4/ref=sr_1_57?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695193864&sprefix=suns%2Caps%2C533&sr=8-57",
      price: "$17.99",
      rank: 10.991,
      rating: "2.9 out of 5 stars",
      reviews: "25 ratings",
      title: "2Pcs Relief Sun Sunscreen Korean Sunscreen, Sunscreen SPF50+ PA+++, Korean Rice Organic Sunscreen Skin Care Solution, Nourishing Skin Protection and UV Defense",
      website: "amazon"
    },
    {

        id: 10,
      availability: "In Stock",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/41vCCia7MOL._SX300_SY300_QL70_ML2_.jpg",
      link: "https://www.amazon.com/Sunscreen-Organic-Solution-Nourishing-Protection/dp/B0CF26JJG4/ref=sr_1_57?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695193976&sprefix=suns%2Caps%2C533&sr=8-57",
      price: "$17.99",
      rank: 10.991,
      rating: "2.9 out of 5 stars",
      reviews: "25 ratings",
      title: "2Pcs Relief Sun Sunscreen Korean Sunscreen, Sunscreen SPF50+ PA+++, Korean Rice Organic Sunscreen Skin Care Solution, Nourishing Skin Protection and UV Defense",
      website: "amazon"
    },
    {
        id: 11,
      availability: "In Stock",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/41vCCia7MOL._SX300_SY300_QL70_ML2_.jpg",
      link: "https://www.amazon.com/Sunscreen-Organic-Solution-Nourishing-Protection/dp/B0CF26JJG4/ref=sr_1_57?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695194088&sprefix=suns%2Caps%2C533&sr=8-57",
      price: "$17.99",
      rank: 10.991,
      rating: "2.9 out of 5 stars",
      reviews: "25 ratings",
      title: "2Pcs Relief Sun Sunscreen Korean Sunscreen, Sunscreen SPF50+ PA+++, Korean Rice Organic Sunscreen Skin Care Solution, Nourishing Skin Protection and UV Defense",
      website: "amazon"
    },
    {
        id: 12,
      availability: "In Stock",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/41vCCia7MOL._SX300_SY300_QL70_ML2_.jpg",
      link: "https://www.amazon.com/Sunscreen-Organic-Solution-Nourishing-Protection/dp/B0CF26JJG4/ref=sr_1_57?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695194220&sprefix=suns%2Caps%2C533&sr=8-57",
      price: "$17.99",
      rank: 10.991,
      rating: "2.9 out of 5 stars",
      reviews: "25 ratings",
      title: "2Pcs Relief Sun Sunscreen Korean Sunscreen, Sunscreen SPF50+ PA+++, Korean Rice Organic Sunscreen Skin Care Solution, Nourishing Skin Protection and UV Defense",
      website: "amazon"
    },
    {
        id: 13,
      availability: "In Stock",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/41vCCia7MOL._SX300_SY300_QL70_ML2_.jpg",
      link: "https://www.amazon.com/Sunscreen-Organic-Solution-Nourishing-Protection/dp/B0CF26JJG4/ref=sr_1_57?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695194332&sprefix=suns%2Caps%2C533&sr=8-57",
      price: "$17.99",
      rank: 10.991,
      rating: "2.9 out of 5 stars",
      reviews: "25 ratings",
      title: "2Pcs Relief Sun Sunscreen Korean Sunscreen, Sunscreen SPF50+ PA+++, Korean Rice Organic Sunscreen Skin Care Solution, Nourishing Skin Protection and UV Defense",
      website: "amazon"
    },
    {
        id: 14,
      availability: "In Stock",
      category: "watch",
      image_url: "https://m.media-amazon.com/images/I/81SkKZjDDyL.__AC_SX342_SY445_QL70_ML2_.jpg",
      link: "https://www.amazon.com/Amazon-Essentials-Silver-Tone-Black-Strap/dp/B07YQFST6X/ref=sr_1_5?crid=3D72CH8G1PIYQ&keywords=watch&qid=1695194451&sprefix=watc%2Caps%2C427&sr=8-5",
      price: "$19.00",
      rank: 1817.04,
      rating: "4.4 out of 5 stars",
      reviews: "3,637 ratings",
      title: "Amazon Essentials Men's Easy to Read Strap Watch",
      website: "amazon"
    },
    {
        id: 15,
      availability: "In Stock",
      category: "watch",
      image_url: "https://m.media-amazon.com/images/I/81SkKZjDDyL.__AC_SX342_SY445_QL70_ML2_.jpg",
      link: "https://www.amazon.com/Amazon-Essentials-Silver-Tone-Black-Strap/dp/B07YQFST6X/ref=sr_1_5?crid=3D72CH8G1PIYQ&keywords=watch&qid=1695194471&sprefix=watc%2Caps%2C427&sr=8-5",
      price: "$19.00",
      rank: 1817.04,
      rating: "4.4 out of 5 stars",
      reviews: "3,637 ratings",
      title: "Amazon Essentials Men's Easy to Read Strap Watch",
      website: "amazon"
    },
     
    
  ];
  
  // Make sure to add the new data without removing the existing data in the `staticData` array.
  