export const staticData = [
    {
      id: 1,
      availability: "In Stock",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/41tTwTi8GdL._SX300_SY300_QL70_ML2_.jpg",
      link: "https://www.amazon.com/Banana-Boat-Sunscreen-Lotion-Formula/dp/B004CDV7EY/ref=sr_1_53?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695193864&sprefix=suns%2Caps%2C533&sr=8-53",
      price: "$10.97",
      rank: 10407.373,
      rating: "4.7 out of 5 stars",
      reviews: "20,816 ratings",
      title: "Banana Boat Sport Ultra SPF 50 Sunscreen Lotion, 12oz | Banana Boat Sunscreen SPF 50 Lotion, Oxybenzone Free Sunscreen, Sunblock Lotion, Family Size Sunscreen SPF 50, 12oz",
      website: "amazon"
    }, 
    {
        id: 2,
        availability: "In Stock",
        category: "sunscreen",
        image_url: "https://m.media-amazon.com/images/I/31eDUkXftCL._SX300_SY300_QL70_ML2_.jpg",
        link: "https://www.amazon.com/Thinkbaby-Safe-Sunscreen-SPF-ounce/dp/B00JJZN1HG/ref=sr_1_55?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695194088&sprefix=suns%2Caps%2C533&sr=8-55",
        price: "$18.19",
        rank: 9829.651,
        rating: "4.7 out of 5 stars",
        reviews: "19,662 ratings",
        title: "Thinkbaby SPF 50+ Baby Sunscreen \u2013 Safe, Natural Sunblock for Babies - Water Resistant Sun Cream \u2013 Broad Spectrum UVA/UVB Sun Protection \u2013 Vegan Mineral Sun Lotion, 6oz",
        website: "amazon"
    },
    {
        id: 3,
        availability: "In Stock",
        category: "sunscreen",
        image_url: "https://m.media-amazon.com/images/I/41KlZtBBuoL._SX300_SY300_QL70_ML2_.jpg",
        link: "https://www.amazon.com/sspa/click?ie=UTF8&spc=MTo3MDA2MTg4NjUxNTI2NjI3OjE2OTUxOTQyMjA6c3BfbXRmOjIwMDEzNDYwNTY4MTM5ODo6MDo6&url=%2FSun-Bum-Moisturizing-SPF-Hypoallergenic%2Fdp%2FB004XGPM32%2Fref%3Dsr_1_59_sspa%3Fcrid%3DBCICLEMKVXND%26keywords%3Dsunscreen%26qid%3D1695194220%26sprefix%3Dsuns%252Caps%252C533%26sr%3D8-59-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9tdGY%26psc%3D1",
        price: "$18.49",
        rank: 9592.631,
        rating: "4.8 out of 5 stars",
        reviews: "19,188 ratings",
        title: "Sun Bum Original SPF 50 Sunscreen Lotion | Vegan and Hawaii 104 Reef Act Compliant (Octinoxate & Oxybenzone Free) Broad Spectrum Moisturizing UVA/UVB Sunscreen with Vitamin E | 8 oz",
        website: "amazon"
    },
    {
        id: 4,
        availability: "In Stock",
        category: "sunscreen",
        image_url: "https://m.media-amazon.com/images/I/41jo8M1fchL._SX300_SY300_QL70_ML2_.jpg",
        link: "https://www.amazon.com/sspa/click?ie=UTF8&spc=MTo0NjQ1NzA4NTU0OTI4NjI3OjE2OTUxOTQwODg6c3BfbXRmOjIwMDA1ODY1NTY5ODI5ODo6MDo6&url=%2FNeutrogena-Resistant-Sunscreen-Spectrum-Fast-Absorbing%2Fdp%2FB00AEN4QZ8%2Fref%3Dsr_1_60_sspa%3Fcrid%3DBCICLEMKVXND%26keywords%3Dsunscreen%26qid%3D1695194088%26sprefix%3Dsuns%252Caps%252C533%26sr%3D8-60-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9tdGY%26psc%3D1",
        price: "$8.65",
        rank: 8743.605,
        rating: "4.7 out of 5 stars",
        reviews: "17,488 ratings",
        title: "Neutrogena Beach Defense Water-Resistant Face & Body SPF 70 Sunscreen Lotion with Broad Spectrum UVA/UVB Protection, Oil-Free Fast-Absorbing Sunscreen Lotion, Oxybenzone-Free, 6.7 oz",
        website: "amazon"
    },
    {
        id: 5,
        availability: "In Stock",
        category: "sunscreen",
        image_url: "https://m.media-amazon.com/images/I/418JGmZbJkL._SX300_SY300_QL70_ML2_.jpg",
        link: "https://www.amazon.com/Neutrogena-Dry-Touch-Resistant-Non-Greasy-Sunscreen/dp/B000EPA4GQ/ref=sr_1_72?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695193864&sprefix=suns%2Caps%2C533&sr=8-72",
        price: "$9.15",
        rank: 8045.545,
        rating: "4.6 out of 5 stars",
        reviews: "16,092 ratings",
        title: "Neutrogena Ultra Sheer Dry-Touch Sunscreen Lotion, Broad Spectrum SPF 55 UVA/UVB Protection, Lightweight Water Resistant Face & Body Sunscreen, Non-Greasy, Travel Size, 3 fl. oz",
        website: "amazon"
    },
    {
        id: 6,
        availability: "In Stock",
        category: "sunscreen",
        image_url: "https://m.media-amazon.com/images/I/31ZZf0Q6xiL._SX300_SY300_QL70_ML2_.jpg",
        link: "https://www.amazon.com/Hawaiian-Tropic-Lotion-Sunscreen-Radiance/dp/B0031O5QF6/ref=sr_1_74?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695193864&sprefix=suns%2Caps%2C533&sr=8-74",
        price: "$9.68",
        rank: 6229.512,
        rating: "4.8 out of 5 stars",
        reviews: "12,460 ratings",
        title: "Hawaiian Tropic Sheer Touch Lotion, 8oz | Hawaiian Tropic Sunscreen SPF 30, Sunblock, Broad Spectrum Sunscreen, Oxybenzone Free Sunscreen, Body Sunscreen SPF 30, 8oz",
        website: "amazon"
    },
    {
        id: 7,
        availability: "In Stock",
        category: "sunscreen",
        image_url: "https://m.media-amazon.com/images/I/41WFXM5LO5L._SX300_SY300_QL70_ML2_.jpg",
        link: "https://www.amazon.com/Aveeno-Continuous-Protection-Sunscreen-Water-Resistant/dp/B07LCW7CZD/ref=sr_1_65?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695193864&sprefix=suns%2Caps%2C533&sr=8-65",
        price: "$9.80",
        rank: 4232.97,
        rating: "4.5 out of 5 stars",
        reviews: "8,467 ratings",
        title: "Aveeno Kids Continuous Protection Zinc Oxide Mineral Sunscreen Lotion for Children's Sensitive Skin with Broad Spectrum SPF 50, Tear-Free, Sweat- & Water-Resistant, Non-Greasy, 3 fl. oz",
        website: "amazon"
    },
    {
        id: 8,
        availability: "In Stock",
        category: "sunscreen",
        image_url: "https://m.media-amazon.com/images/I/71WxAKjhbYL.__AC_SX300_SY300_QL70_ML2_.jpg",
        link: "https://www.amazon.com/Amazon-Brand-Sunscreen-Spectrum-Protection/dp/B07WGV6Q45/ref=sr_1_66?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695193864&sprefix=suns%2Caps%2C533&sr=8-66",
        price: "$5.86",
        rank: 3368.364,
        rating: "4.5 out of 5 stars",
        reviews: "6,737 ratings",
        title: "Amazon Brand - Solimo Sport Sunscreen Lotion, SPF 50, Reef Friendly (Octinoxate & Oxybenzone Free), Broad Spectrum UVA/UVB Protection, 8 Fluid Ounce",
        website: "amazon"
    },
    {
        id: 9,
        availability: "In Stock",
        category: "sunscreen",
        image_url: "https://m.media-amazon.com/images/I/41brPxL1qiL._SX300_SY300_QL70_ML2_.jpg",
        link: "https://www.amazon.com/CeraVe-Sunscreen-Mineral-Adults-Fragrance/dp/B00CICLTAI/ref=sr_1_63?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695193864&sprefix=suns%2Caps%2C533&sr=8-63",
        price: "$8.99",
        rank: 2942.551,
        rating: "4.5 out of 5 stars",
        reviews: "5,886 ratings",
        title: "CeraVe Mineral Sunscreen Stick for Kids & Adults | 100% Mineral Sunscreen, Zinc Oxide & Titanium Dioxide with Hyaluronic Acid and Ceramides | Broad Spectrum SPF 50 | Fragrance Free | 0.47 Ounce",
        website: "amazon"
    },
    {

        id: 10,
        availability: "In Stock",
        category: "sunscreen",
        image_url: "https://m.media-amazon.com/images/I/418Ye14DZvL._SX300_SY300_QL70_ML2_.jpg",
        link: "https://www.amazon.com/Neutrogena-Invisible-Sunscreen-Hydrating-Antioxidants/dp/B08HWK8F9T/ref=sr_1_80?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695193864&sprefix=suns%2Caps%2C533&sr=8-80",
        price: "$12.07",
        rank: 2333.743,
        rating: "4.5 out of 5 stars",
        reviews: "4,669 ratings",
        title: "Neutrogena Invisible Daily Defense Face Sunscreen + Hydrating Serum with Broad Spectrum SPF 60+ & Antioxidants to Help Skin Glow, Oil-Free, Fragrance Free, 1.7 fl. oz",
        website: "amazon"
    },
    {
        id: 11,
        availability: "In Stock",
        category: "sunscreen",
        image_url: "https://m.media-amazon.com/images/I/31boayTZCUS._SY445_SX342_QL70_ML2_.jpg",
        link: "https://www.amazon.com/Bondi-Sands-Fragrance-Protection-Non-Greasy/dp/B08Q86TZMK/ref=sr_1_58?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695193864&sprefix=suns%2Caps%2C533&sr=8-58",
        price: "$6.99",
        rank: 2250.7509999999997,
        rating: "4.5 out of 5 stars",
        reviews: "4,502 ratings",
        title: "Bondi Sands Fragrance Free Daily Sunscreen Face Lotion SPF 50 | Hydrating UVA + UVB Protection, Non-Greasy, Gentle, Water Resistant | 2.53 Oz/75 mL",
        website: "amazon"
    },
    {
        id: 12,
        availability: "In Stock",
        category: "sunscreen",
        image_url: "https://m.media-amazon.com/images/I/41LmatLwOQL._SY445_SX342_QL70_ML2_.jpg",
        link: "https://www.amazon.com/EltaMD-Sunscreen-Broad-Spectrum-Protection-Lightweight/dp/B08N66R447/ref=sr_1_83?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695193864&sprefix=suns%2Caps%2C533&sr=8-83",
        price: "$34.00",
        rank: 943.0600000000001,
        rating: "4.6 out of 5 stars",
        reviews: "1,892 ratings",
        title: "EltaMD UV Sheer Face Sunscreen, SPF 50+ Hydrating Sunscreen for Face, Helps Even Skin Tones and Soothe Heated Skin, Water Resistant up to 80 Minutes, No White Cast, Travel Size Sunscreen, 1.7 oz Tube",
        website: "amazon"
    },
    {
        id: 13,
        availability: "In Stock",
        category: "sunscreen",
        image_url: "https://m.media-amazon.com/images/I/31NzHB+AwxL._SY300_SX300_.jpg",
        link: "https://www.amazon.com/Paulas-Choice-Non-Greasy-Sunscreen-Protection/dp/B00949DNDO/ref=sr_1_71?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695193864&sprefix=suns%2Caps%2C533&sr=8-71",
        price: "$22.00",
        rank: 863.7099999999999,
        rating: "4.1 out of 5 stars",
        reviews: "1,731 ratings",
        title: "Paula's Choice Extra Care Non Greasy, Oil Free Face & Body Sunscreen SPF 50, UVA & UVB Protection, Water & Sweat Resistant, 5 Ounce",
        website: "amazon"
    },
    {
        id: 14,
        availability: "In Stock",
        category: "sunscreen",
        image_url: "https://m.media-amazon.com/images/I/41-Hzr2w9WL._SX300_SY300_QL70_ML2_.jpg",
        link: "https://www.amazon.com/sspa/click?ie=UTF8&spc=MTo0NjQ1NzA4NTU0OTI4NjI3OjE2OTUxOTQwODg6c3BfbXRmOjIwMDExODg4MTM2ODM5ODo6MDo6&url=%2FNeutrogena-Purescreen-Sunscreen-Resistant-Fragrance%2Fdp%2FB0BLRGCTS1%2Fref%3Dsr_1_67_sspa%3Fcrid%3DBCICLEMKVXND%26keywords%3Dsunscreen%26qid%3D1695194088%26sprefix%3Dsuns%252Caps%252C533%26sr%3D8-67-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9tdGY%26psc%3D1",
        price: "$13.59",
        rank: 860.531,
        rating: "3.9 out of 5 stars",
        reviews: "1,723 ratings",
        title: "Neutrogena Purescreen+ Tinted Sunscreen for Face with SPF 30, Broad Spectrum Mineral Sunscreen with Zinc Oxide and Vitamin E, Water Resistant, Fragrance Free, Medium, 1.1 fl oz",
        website: "amazon"
    },
    {
        id: 15,
        availability: "In Stock",
        category: "sunscreen",
        image_url: "https://m.media-amazon.com/images/I/41SalszW3qL._SY445_SX342_QL70_ML2_.jpg",
        link: "https://www.amazon.com/Fallene-Flawless-Complexion-50-Ounce/dp/B00QHVJL5G/ref=sr_1_79?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695193864&sprefix=suns%2Caps%2C533&sr=8-79",
        price: "$27.50",
        rank: 691.2,
        rating: "4.5 out of 5 stars",
        reviews: "1,387 ratings",
        title: "C\u014dTZ Flawless Complexion Tinted Facial Mineral Sunscreen Broad Spectrum SPF 50; 2.5 oz / 70 g",
        website: "amazon"
    },
    {
        id: 16,
        availability: "Only 2 left in stock - order soon",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/51zX0T24VWL._SX300_SY300_QL70_ML2_.jpg",
      link: "https://www.amazon.com/CeraVe-Hydrating-Sunscreen-Hyaluronic-Niacinamides/dp/B0BFJVZPDC/ref=sr_1_75?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695194088&sprefix=suns%2Caps%2C533&sr=8-75",
      price: "$12.97",
      rank: 440.15299999999996,
      rating: "4.5 out of 5 stars",
      reviews: "882 ratings",
      title: "CeraVe Hydrating Sheer Sunscreen SPF 30 for Face and Body | Mineral Sunscreen & Chemical Sunscreen with Zinc Oxide, Hyaluronic Acid, Niacinamides and Ceramides| Paraben Free Fragrance Free | 3 Ounces",
      website: "amazon"
      },
      {
        id: 17,
        availability: "In Stock",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/313QGaGyn3L._SX300_SY300_QL70_ML2_.jpg",
      link: "https://www.amazon.com/Supergoop-PLAY-Everyday-SPF-Lotion/dp/B087H3JHZN/ref=sr_1_54?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695193864&sprefix=suns%2Caps%2C533&sr=8-54",
      price: "$33.99",
      rank: 379.571,
      rating: "4.7 out of 5 stars",
      reviews: "765 ratings",
      title: "Supergoop! Mini PLAY Everyday Sunscreen Lotion SPF 30 5.5 oz/ 162 mL",
      website: "amazon"
      },
      {
        id: 18,
        availability: "In Stock",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/41ECZW5jSoL._SY445_SX342_QL70_ML2_.jpg",
      link: "https://www.amazon.com/EltaMD-Sunscreen-Broad-Spectrum-Water-Resistant-Non-Greasy/dp/B08FP3S97T/ref=sr_1_76?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695193864&sprefix=suns%2Caps%2C533&sr=8-76",
      price: "$34.00",
      rank: 333.55,
      rating: "4.5 out of 5 stars",
      reviews: "673 ratings",
      title: "EltaMD UV Active SPF 50+ Mineral Sunscreen Lotion, Broad Spectrum Physical Sunscreen for Face and Body, Water-Resistant Up to 80 Minutes, Oil-Free, Non-Greasy, Full Body Sunscreen",
      website: "amazon"
      },
      {
        id: 19,
        availability: "In Stock",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/41+zD-AlDEL._SY300_SX300_.jpg",
      link: "https://www.amazon.com/Naturium-Moisturizer-Moisturizing-Sunscreen-Protector/dp/B0BQCQ3WD7/ref=sr_1_64?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695193864&sprefix=suns%2Caps%2C533&sr=8-64",
      price: "$21.99",
      rank: 242.75099999999998,
      rating: "4.5 out of 5 stars",
      reviews: "489 ratings",
      title: "Naturium Dew-Glow Moisturizer SPF 50 PA++++, Daily Moisturizing Sunscreen & Face Primer, Skin Protector with Dewy Finish, 1.7 oz",
      website: "amazon"
      },
      {
        id: 20,
        availability: "In Stock",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/31ff-whk0jL._SY445_SX342_QL70_ML2_.jpg",
      link: "https://www.amazon.com/Shiseido-Ultimate-Protector-Lotion-Broad-Spectrum/dp/B0921KVV27/ref=sr_1_78?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695193864&sprefix=suns%2Caps%2C533&sr=8-78",
      price: "$30.00",
      rank: 213.96,
      rating: "4.6 out of 5 stars",
      reviews: "433 ratings",
      title: "Shiseido Clear Sunscreen Stick SPF 50+ - Invisible Broad-Spectrum Face Sunscreen - Wear Under & Over Makeup - Lightweight Formula - All Skin Types",
      website: "amazon"
      },
      {
        id: 21,
        availability: "In Stock",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/41Ef9gHiz5L._SY445_SX342_QL70_ML2_.jpg",
      link: "https://www.amazon.com/Murad-Broad-Spectrum-Mineral-Sunscreen/dp/B075S1BM4V/ref=sr_1_77?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695193864&sprefix=suns%2Caps%2C533&sr=8-77",
      price: "$69.00",
      rank: 166.54,
      rating: "4.4 out of 5 stars",
      reviews: "346 ratings",
      title: "Murad Environmental Shield City Skin Age Defense Broad Spectrum SPF 50-100% Mineral Sunscreen - Blue Light Defense - SPF 50 Environmental Defense Sunscreen - Light Sunscreen for Face",
      website: "amazon"
      },
      {
        id: 22,
        availability: "In Stock",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/31OczkDNwiL._SX300_SY300_QL70_ML2_.jpg",
      link: "https://www.amazon.com/sspa/click?ie=UTF8&spc=MTozNzYxNjE3OTQ4MjY4NjI3OjE2OTUxOTM5Nzc6c3BfbXRmOjMwMDA0MTQ3NjczNTUwMjo6MDo6&url=%2FOars-Alps-Everyday-Moisturizer-Hyaluronic%2Fdp%2FB08YRPSQ7M%2Fref%3Dsr_1_70_sspa%3Fcrid%3DBCICLEMKVXND%26keywords%3Dsunscreen%26qid%3D1695193976%26sprefix%3Dsuns%252Caps%252C533%26sr%3D8-70-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9tdGY%26psc%3D1",
      price: "$21.99",
      rank: 132.71099999999998,
      rating: "4.1 out of 5 stars",
      reviews: "269 ratings",
      title: "Oars + Alps SPF 37 Sunscreen and Everyday Anti Aging Face Moisturizer, Infused with Hyaluronic Acid, Vitamin E and Vitamin B5, TSA Friendly, 2 Fl Oz",
      website: "amazon"
      },
      {
        id: 23,
        availability: "In Stock",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/31ZjIHuUZML._SX300_SY300_QL70_ML2_.jpg",
      link: "https://www.amazon.com/sspa/click?ie=UTF8&spc=MTo1MzA4MjE2NzQxOTQwNjI3OjE2OTUxOTM4NjQ6c3BfbXRmOjMwMDAwNTQ4MTYyNzAwMjo6MDo6&url=%2FGood-Molecules-Sheer-Mineral-Sunscreen%2Fdp%2FB0BNC52HLN%2Fref%3Dsr_1_69_sspa%3Fcrid%3DBCICLEMKVXND%26keywords%3Dsunscreen%26qid%3D1695193864%26sprefix%3Dsuns%252Caps%252C533%26sr%3D8-69-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9tdGY%26psc%3D1",
      price: "$12.00",
      rank: 102.23,
      rating: "4.3 out of 5 stars",
      reviews: "206 ratings",
      title: "Good Molecules Sheer Mineral Sunscreen SPF 30 50ml/1.7oz - Invisible, Sheer, Zinc Oxide Sunscreen with Hyaluronic Acid - Reef-Safe, Hydrating, Non-greasy UVA/UVB Protection - Skin Care For Face",
      website: "amazon"
      },
      {
        id: 24,
        availability: "In Stock",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/312pSZ7-bXL._SX300_SY300_QL70_ML2_.jpg",
      link: "https://www.amazon.com/Haruharu-Sunscreen-1-69fl-oz-Including-Sensitive/dp/B0BZ3Q4ZD9/ref=sr_1_73?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695193864&sprefix=suns%2Caps%2C533&sr=8-73",
      price: "$12.99",
      rank: 74.11099999999999,
      rating: "4.1 out of 5 stars",
      reviews: "150 ratings",
      title: "Haruharu Wonder Black Rice Pure Mineral Relief Daily Sunscreen 50ml (1.69fl.oz), Reef Safe Formula, For All Skin Types Including Sensitive Skin",
      website: "amazon"
      },
      {
        id: 25,
        availability: "In Stock",
      category: "sunscreen",
      image_url: "https://m.media-amazon.com/images/I/41vCCia7MOL._SX300_SY300_QL70_ML2_.jpg",
      link: "https://www.amazon.com/Sunscreen-Organic-Solution-Nourishing-Protection/dp/B0CF26JJG4/ref=sr_1_57?crid=BCICLEMKVXND&keywords=sunscreen&qid=1695193864&sprefix=suns%2Caps%2C533&sr=8-57",
      price: "$17.99",
      rank: 10.991,
      rating: "2.9 out of 5 stars",
      reviews: "25 ratings",
      title: "2Pcs Relief Sun Sunscreen Korean Sunscreen, Sunscreen SPF50+ PA+++, Korean Rice Organic Sunscreen Skin Care Solution, Nourishing Skin Protection and UV Defense",
      website: "amazon"
      },
      {
        id: 26,
        availability: "In Stock",
      category: "watch",
      image_url: "https://m.media-amazon.com/images/I/81SkKZjDDyL.__AC_SX342_SY445_QL70_ML2_.jpg",
      link: "https://www.amazon.com/Amazon-Essentials-Silver-Tone-Black-Strap/dp/B07YQFST6X/ref=sr_1_5?crid=3D72CH8G1PIYQ&keywords=watch&qid=1695194451&sprefix=watc%2Caps%2C427&sr=8-5",
      price: "$19.00",
      rank: 1817.04,
      rating: "4.4 out of 5 stars",
      reviews: "3,637 ratings",
      title: "Amazon Essentials Men's Easy to Read Strap Watch",
      website: "amazon"
      },
      {
        id: 27,
        availability: "In Stock",
      category: "watch",
      image_url: "https://m.media-amazon.com/images/I/81D4NZ2OtZL.__AC_SX300_SY300_QL70_ML2_.jpg",
      link: "https://www.amazon.com/Invicta-1515-Collection-Ion-Plated-Cloth-Covered/dp/B005FMZY36/ref=sr_1_6?crid=3D72CH8G1PIYQ&keywords=watch&qid=1695194451&sprefix=watc%2Caps%2C427&sr=8-6",
      price: "$49.57",
      rank: 1043.503,
      rating: "4.6 out of 5 stars",
      reviews: "2,096 ratings",
      title: "Invicta Men's I Force Collection Chronograph Strap Watch",
      website: "amazon"
      },
       
       
  ];
  
  // Make sure to add the new data without removing the existing data in the `staticData` array.
  